### ISSUE TITLE
Feature Request - Web Interface

### ISSUE THREAD

**Issue by DykstraSound** [Keith-N/KaN_Gauge_V2#1]
It would be quite helpful if the web interface would show the currently set values for the gauge.  Something along the lines of when you select the top arc it would show that it is set as Lambda, and the min/max limits would show in that section. 
Would also be nice to have the min/max values for any of the gauges visible and configurable simultaneously.

**Comment by Keith-N** [comment]
I've wanted to get something like this into the interface to improve ease of use. I'm not sure what the best way to do this is, or how much of an overhaul there will need to be, so it may take some time before you see any major improvement here. I could likely make some modifications to the current interface to at least make it possible to simultaneously adjust min/max/alert values at once.

**Comment by DykstraSound** [comment]
That would be helpful, for sure.  I've got a friend that is a web dev, so I might have a chat with him and show him the source code and see what he thinks.

**Comment by Keith-N** [comment]
I have updated the interface to expand out some of the options for simultaneous configuration for min/max/alert and the custom LED colors.
https://github.com/Keith-N/KaN_Gauge_V2/releases/tag/WiFi_ConfigExp

**Comment by Keith-N** [comment]
Starting to work on this again. Made a test build which shows some of the current configuration options. Still needs work to show more on the configuration pages.
https://github.com/Keith-N/KaN_Gauge_V2/releases/tag/v0.44_1

**Comment by Keith-N** [comment]
Release 0.45 will show current configuration settings while in the WiFi configuration interface
https://github.com/Keith-N/KaN_Gauge_V2/releases/tag/v0.45
