### ISSUE TITLE
Add Fuel Temperature to data points

### ISSUE THREAD

**Issue by DykstraSound** [Keith-N/KaN_Gauge_V2#2]
According to the new release of the BMM firmware, they have corrected the fuel temperature derivative from the flex fuel sensor.  Can we get this added to the available options to be displayed on the gauge?

**Comment by Keith-N** [comment]
https://github.com/Keith-N/KaN_Gauge_V2/releases/tag/Sensor_fuelTemperature

Added, see if this build works for you

**Comment by DykstraSound** [comment]
The fuel temp is pulling in C.  Fuel Temp F just gives an "INF" which I'm guessing is an infinite value.

**Comment by Keith-N** [comment]
I found that it was not being converted to F using the C value. I have updated the bin https://github.com/Keith-N/KaN_Gauge_V2/releases/tag/Sensor_fuelTemperature

**Comment by DykstraSound** [comment]
Was able to test this today, and fuel temp is reading F.  Based on the location of my sensor currently, it was reading a few degrees cooler than ambient temp and I fell pretty good that it's an accurate reading. I'll continue to monitor the next couple of times I drive it, but even when it was set to C it appeared to be reading and displaying just fine. I'll let you decide if you want to close this issue.

**Comment by Keith-N** [comment]
Added to 0.41
