### ISSUE TITLE
Add Fuel Level to Data Points **UPCOMING**

### ISSUE THREAD

**Issue by DykstraSound** [Keith-N/KaN_Gauge_V2#3]
I'm working with the guys to get the ECU to read fuel level. We haven't got it nailed down yet, but once we get it ironed out the design for NB2 will be updated to include it out of the box. Once it's added to the CAN broadcast I'd like to have it on the gauge.

**Comment by DykstraSound** [comment]
It looks like we've got the fuel level running correctly in a snapshot.  Is this something you'll have to wait for a release to implement?

**Comment by Keith-N** [comment]
Adding extra things isn't an issue. If it isn't part of the broadcast on whichever firmware you are using it just wont be able to update it on the gauge. The only time it really becomes an issue is when addresses or data position change and conflict with something between ECU firmware versions. This should be as easy to add as the last one. I haven't looked back at where it is in the broadcast yet, but I don't recall it replacing something else.

**Comment by Keith-N** [comment]
I'm getting back to this now and, fuel level should already be available on the gauge. Have you tried it and had issues?

**Comment by DykstraSound** [comment]
I found it on there while I was working through the hardware stuff on the ECU. Once I had it set up in TS correctly it read no problem.
